# Etapa de construcció
FROM node:latest as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# Etapa de desplegament
FROM nginx:latest
COPY --from=build /app/dist/front_chatbot/browser /usr/share/nginx/html
EXPOSE 80